#!/bin/bash
rm -f CMakeCache.txt
rm -rf CMakeFiles
cmake -D WITH_EXTRA_WARNINGS=ON \
      -D WITH_SOCKET_LOG=ON \
      -D WITH_INTERNAL_TRACE=ON \
      -D CMAKE_INSTALL_PREFIX:PATH=/tmp \
      "$@" "$(dirname "$0")" &&
make clean
