#!/usr/bin/env bash
#
# Copyright 2025 AVSystem <avsystem@avsystem.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

. "$(dirname "$0")/utils.sh"

function die() {
    echo -e "$@" >&2
    exit 1
}

which gcc || die "gcc not found, exiting"
which lcov || die "lcov not found, exiting"
which genhtml || die "genhtml not found, exiting"

GCC_VERSION=$(gcc --version 2>&1 | head -n 1 | awk 'END {print $NF}')
GCC_MAJOR_VERSION=${GCC_VERSION%%.*}
LCOV_VERSION=$(lcov --version 2>&1 | head -n 1 | awk 'END {print $NF}')
LCOV_MAJOR_VERSION=${LCOV_VERSION%%.*}

if [ "$LCOV_MAJOR_VERSION" -gt 1 ]; then
    LCOV_ADDITIONAL_OPTS="--rc branch_coverage=1 --ignore-errors mismatch"
else
    LCOV_ADDITIONAL_OPTS="--rc lcov_branch_coverage=1"
fi

[[ "$PROJECT_ROOT" ]] || PROJECT_ROOT="$(dirname "$(dirname "$(canonicalize "$0")")")"

rm -rf "$PROJECT_ROOT/build/coverage"
mkdir -p "$PROJECT_ROOT/build/coverage"
pushd "$PROJECT_ROOT/build/coverage"
    "$PROJECT_ROOT/devconfig" -DCMAKE_C_FLAGS="-std=c99 -D_POSIX_C_SOURCE=200809L -g -O0 --coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage" "$@"
    make check -j$(num_processors)
    mkdir -p "$PROJECT_ROOT/coverage"
    lcov $LCOV_ADDITIONAL_OPTS -c -d . -o coverage.info --gcov-tool /usr/bin/gcov-$GCC_MAJOR_VERSION
    lcov $LCOV_ADDITIONAL_OPTS --remove coverage.info "$PROJECT_ROOT/tests/*" "/usr/*" "$PROJECT_ROOT/include_public/*" -o coverage.info
    genhtml coverage.info --branch-coverage --function-coverage --output-directory "$PROJECT_ROOT/coverage"
popd

cat <<EOF

-----
Coverage report generated in $PROJECT_ROOT/coverage
EOF
